# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8102689f95223fdc3f405f0120dd939e99ea960708661a0d95e3ab3a61d7c3223f4a94a8996b1ef5d56807bb5bfd7cb647c36d0642efc2a80d8b716bfce3887b

test:
  secret_key_base: 6afab188194f9912bd3342cc450af3f8f981d7b816313f88765e9d3a9afb470af8938218689a45842a740a35cc4b850cf603859eaf7195c82a8b1d424d08c01a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
